version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: haber_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=haberdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - haber-network

  redis:
    image: redis:6-alpine
    container_name: haber_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - haber-network

  minio:
    image: minio/minio:latest
    container_name: haber_minio
    ports:
      - "9000:9000"      # API
      - "9001:9001"      # Web UI
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    restart: unless-stopped
    command: server --console-address ":9001" /data
    networks:
      - haber-network

  adminer:
    image: adminer
    container_name: haber_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - haber-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  haber-network:
    driver: bridge 