version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: haber_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=haberdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - haber-network

  redis:
    image: redis:6-alpine
    container_name: haber_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - haber-network

  adminer:
    image: adminer
    container_name: haber_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - haber-network

volumes:
  postgres_data:
  redis_data:

networks:
  haber-network:
    driver: bridge 